"""Production v2 evidence graph and resolver contracts."""

from __future__ import annotations

from .adapter import Adapter, AdapterArtifact, AdapterInput
from .compatibility import LEGACY_COMPATIBILITY_VERSION, legacy_compatibility_document
from .contracts import (
    BASELINE_SCHEMA_VERSION,
    CONFIG_SCHEMA_VERSION,
    EVIDENCE_POLICY_SCHEMA_ID,
    EVIDENCE_POLICY_SCHEMA_VERSION,
    EXCEPTION_SCHEMA_VERSION,
    FACT_GRAPH_VERSION,
    MANIFEST_SCHEMA_VERSION,
    REPORT_SCHEMA_ID,
    REPORT_SCHEMA_VERSION,
    SARIF_MAPPING_VERSION,
)
from .explain import (
    EXPLAIN_ADAPTER_VIEW_VERSION,
    AdapterExplanation,
    CapabilityExplanation,
    explain_adapter_document,
    render_adapter_explanation,
)
from .fingerprint import Fingerprint, endpoint_fingerprint, proof_fingerprint
from .graph import EvidenceGraph, GraphValidationError
from .manifest import ManifestError, RulepackManifest, load_manifest, parse_manifest
from .model import (
    Capability,
    CapabilityProvenance,
    CoverageRecord,
    CoverageStatus,
    Diagnostic,
    DiagnosticLevel,
    EndpointResolution,
    EndpointVerdict,
    EvidenceAssociation,
    Fact,
    FactKind,
    Proof,
    ProofKind,
    Relation,
    RelationKind,
    Scope,
    ScopeKind,
    SourceSpan,
    Subject,
    SubjectKind,
    UnresolvedRecord,
)
from .package import (
    ActivationEvidence,
    ApplicabilityResult,
    ApplicabilityState,
    CapabilityMaturity,
    OwnershipDecision,
    OwnershipState,
    PackageLifecycle,
    ReportedCapability,
)
from .policy import (
    CapabilityRequirement,
    EvidenceGateResult,
    EvidencePolicy,
    EvidencePolicyError,
    GateDisposition,
    GateIssue,
    GateIssueKind,
    evaluate_evidence_policy,
    load_evidence_policy,
    parse_evidence_policy,
)
from .report import EvidenceReport, InvocationProvenance, report_document
from .resolver import resolve_endpoints
from .semantics import SemanticKind, SemanticRule

__all__ = [
    "ActivationEvidence",
    "AdapterExplanation",
    "Adapter",
    "AdapterArtifact",
    "AdapterInput",
    "ApplicabilityResult",
    "ApplicabilityState",
    "BASELINE_SCHEMA_VERSION",
    "Capability",
    "CapabilityMaturity",
    "CapabilityProvenance",
    "CONFIG_SCHEMA_VERSION",
    "CapabilityRequirement",
    "CoverageRecord",
    "CoverageStatus",
    "CapabilityExplanation",
    "Diagnostic",
    "DiagnosticLevel",
    "EndpointResolution",
    "EndpointVerdict",
    "EVIDENCE_POLICY_SCHEMA_ID",
    "EVIDENCE_POLICY_SCHEMA_VERSION",
    "EXCEPTION_SCHEMA_VERSION",
    "EXPLAIN_ADAPTER_VIEW_VERSION",
    "EvidenceAssociation",
    "EvidenceGraph",
    "EvidenceGateResult",
    "EvidencePolicy",
    "EvidencePolicyError",
    "EvidenceReport",
    "FACT_GRAPH_VERSION",
    "Fact",
    "FactKind",
    "Fingerprint",
    "GraphValidationError",
    "GateDisposition",
    "GateIssue",
    "GateIssueKind",
    "InvocationProvenance",
    "LEGACY_COMPATIBILITY_VERSION",
    "MANIFEST_SCHEMA_VERSION",
    "ManifestError",
    "OwnershipDecision",
    "OwnershipState",
    "PackageLifecycle",
    "Proof",
    "ProofKind",
    "REPORT_SCHEMA_ID",
    "REPORT_SCHEMA_VERSION",
    "ReportedCapability",
    "Relation",
    "RelationKind",
    "RulepackManifest",
    "SARIF_MAPPING_VERSION",
    "Scope",
    "ScopeKind",
    "SourceSpan",
    "SemanticKind",
    "SemanticRule",
    "Subject",
    "SubjectKind",
    "UnresolvedRecord",
    "endpoint_fingerprint",
    "evaluate_evidence_policy",
    "explain_adapter_document",
    "legacy_compatibility_document",
    "load_manifest",
    "load_evidence_policy",
    "parse_evidence_policy",
    "parse_manifest",
    "proof_fingerprint",
    "report_document",
    "render_adapter_explanation",
    "resolve_endpoints",
]
